name: Release Chrome Extension

on:
  push:
    tags:
      - 'v*' # 当推送 v 开头的标签时触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build extension
        run: npm run build

      - name: Create ZIP file
        run: |
          cd dist
          zip -r ../dist.zip .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist.zip
          token: ${{ secrets.RELEASE_TOKEN }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false 